#  spring.application.name=book-network


spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  application:
    name: book-network
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/V1/